/**
 * Complete metadata for all 114 Surahs of the Quran.
 * Used to enrich the API response with English names and translations.
 */
export interface SurahMeta {
  id: number;
  nameEn: string;
  translation: string;
  type: "Meccan" | "Medinan";
}

export const SURAH_META: SurahMeta[] = [
  { id: 1, nameEn: "Al-Fatihah", translation: "The Opening", type: "Meccan" },
  { id: 2, nameEn: "Al-Baqarah", translation: "The Cow", type: "Medinan" },
  { id: 3, nameEn: "Aal-E-Imran", translation: "The Family of Imran", type: "Medinan" },
  { id: 4, nameEn: "An-Nisa", translation: "The Women", type: "Medinan" },
  { id: 5, nameEn: "Al-Ma'idah", translation: "The Table Spread", type: "Medinan" },
  { id: 6, nameEn: "Al-An'am", translation: "The Cattle", type: "Meccan" },
  { id: 7, nameEn: "Al-A'raf", translation: "The Heights", type: "Meccan" },
  { id: 8, nameEn: "Al-Anfal", translation: "The Spoils of War", type: "Medinan" },
  { id: 9, nameEn: "At-Tawbah", translation: "The Repentance", type: "Medinan" },
  { id: 10, nameEn: "Yunus", translation: "Jonah", type: "Meccan" },
  { id: 11, nameEn: "Hud", translation: "Hud", type: "Meccan" },
  { id: 12, nameEn: "Yusuf", translation: "Joseph", type: "Meccan" },
  { id: 13, nameEn: "Ar-Ra'd", translation: "The Thunder", type: "Medinan" },
  { id: 14, nameEn: "Ibrahim", translation: "Abraham", type: "Meccan" },
  { id: 15, nameEn: "Al-Hijr", translation: "The Rocky Tract", type: "Meccan" },
  { id: 16, nameEn: "An-Nahl", translation: "The Bee", type: "Meccan" },
  { id: 17, nameEn: "Al-Isra", translation: "The Night Journey", type: "Meccan" },
  { id: 18, nameEn: "Al-Kahf", translation: "The Cave", type: "Meccan" },
  { id: 19, nameEn: "Maryam", translation: "Mary", type: "Meccan" },
  { id: 20, nameEn: "Taha", translation: "Ta-Ha", type: "Meccan" },
  { id: 21, nameEn: "Al-Anbiya", translation: "The Prophets", type: "Meccan" },
  { id: 22, nameEn: "Al-Hajj", translation: "The Pilgrimage", type: "Medinan" },
  { id: 23, nameEn: "Al-Mu'minun", translation: "The Believers", type: "Meccan" },
  { id: 24, nameEn: "An-Nur", translation: "The Light", type: "Medinan" },
  { id: 25, nameEn: "Al-Furqan", translation: "The Criterion", type: "Meccan" },
  { id: 26, nameEn: "Ash-Shu'ara", translation: "The Poets", type: "Meccan" },
  { id: 27, nameEn: "An-Naml", translation: "The Ant", type: "Meccan" },
  { id: 28, nameEn: "Al-Qasas", translation: "The Stories", type: "Meccan" },
  { id: 29, nameEn: "Al-Ankabut", translation: "The Spider", type: "Meccan" },
  { id: 30, nameEn: "Ar-Rum", translation: "The Romans", type: "Meccan" },
  { id: 31, nameEn: "Luqman", translation: "Luqman", type: "Meccan" },
  { id: 32, nameEn: "As-Sajdah", translation: "The Prostration", type: "Meccan" },
  { id: 33, nameEn: "Al-Ahzab", translation: "The Combined Forces", type: "Medinan" },
  { id: 34, nameEn: "Saba", translation: "Sheba", type: "Meccan" },
  { id: 35, nameEn: "Fatir", translation: "The Originator", type: "Meccan" },
  { id: 36, nameEn: "Ya-Sin", translation: "Ya-Sin", type: "Meccan" },
  { id: 37, nameEn: "As-Saffat", translation: "Those Ranged in Ranks", type: "Meccan" },
  { id: 38, nameEn: "Sad", translation: "Sad", type: "Meccan" },
  { id: 39, nameEn: "Az-Zumar", translation: "The Groups", type: "Meccan" },
  { id: 40, nameEn: "Ghafir", translation: "The Forgiver", type: "Meccan" },
  { id: 41, nameEn: "Fussilat", translation: "Explained in Detail", type: "Meccan" },
  { id: 42, nameEn: "Ash-Shura", translation: "The Consultation", type: "Meccan" },
  { id: 43, nameEn: "Az-Zukhruf", translation: "The Gold Adornments", type: "Meccan" },
  { id: 44, nameEn: "Ad-Dukhan", translation: "The Smoke", type: "Meccan" },
  { id: 45, nameEn: "Al-Jathiyah", translation: "The Kneeling", type: "Meccan" },
  { id: 46, nameEn: "Al-Ahqaf", translation: "The Curved Sand-hills", type: "Meccan" },
  { id: 47, nameEn: "Muhammad", translation: "Muhammad", type: "Medinan" },
  { id: 48, nameEn: "Al-Fath", translation: "The Victory", type: "Medinan" },
  { id: 49, nameEn: "Al-Hujurat", translation: "The Dwellings", type: "Medinan" },
  { id: 50, nameEn: "Qaf", translation: "Qaf", type: "Meccan" },
  { id: 51, nameEn: "Adh-Dhariyat", translation: "The Winds that Scatter", type: "Meccan" },
  { id: 52, nameEn: "At-Tur", translation: "The Mount", type: "Meccan" },
  { id: 53, nameEn: "An-Najm", translation: "The Star", type: "Meccan" },
  { id: 54, nameEn: "Al-Qamar", translation: "The Moon", type: "Meccan" },
  { id: 55, nameEn: "Ar-Rahman", translation: "The Most Gracious", type: "Medinan" },
  { id: 56, nameEn: "Al-Waqi'ah", translation: "The Event", type: "Meccan" },
  { id: 57, nameEn: "Al-Hadid", translation: "The Iron", type: "Medinan" },
  { id: 58, nameEn: "Al-Mujadilah", translation: "The Pleading Woman", type: "Medinan" },
  { id: 59, nameEn: "Al-Hashr", translation: "The Gathering", type: "Medinan" },
  { id: 60, nameEn: "Al-Mumtahanah", translation: "The Woman to be Examined", type: "Medinan" },
  { id: 61, nameEn: "As-Saff", translation: "The Row", type: "Medinan" },
  { id: 62, nameEn: "Al-Jumu'ah", translation: "Friday", type: "Medinan" },
  { id: 63, nameEn: "Al-Munafiqun", translation: "The Hypocrites", type: "Medinan" },
  { id: 64, nameEn: "At-Taghabun", translation: "Mutual Loss & Gain", type: "Medinan" },
  { id: 65, nameEn: "At-Talaq", translation: "The Divorce", type: "Medinan" },
  { id: 66, nameEn: "At-Tahrim", translation: "The Prohibition", type: "Medinan" },
  { id: 67, nameEn: "Al-Mulk", translation: "The Dominion", type: "Meccan" },
  { id: 68, nameEn: "Al-Qalam", translation: "The Pen", type: "Meccan" },
  { id: 69, nameEn: "Al-Haqqah", translation: "The Inevitable", type: "Meccan" },
  { id: 70, nameEn: "Al-Ma'arij", translation: "The Ways of Ascent", type: "Meccan" },
  { id: 71, nameEn: "Nuh", translation: "Noah", type: "Meccan" },
  { id: 72, nameEn: "Al-Jinn", translation: "The Jinn", type: "Meccan" },
  { id: 73, nameEn: "Al-Muzzammil", translation: "The Enshrouded One", type: "Meccan" },
  { id: 74, nameEn: "Al-Muddaththir", translation: "The Cloaked One", type: "Meccan" },
  { id: 75, nameEn: "Al-Qiyamah", translation: "The Resurrection", type: "Meccan" },
  { id: 76, nameEn: "Al-Insan", translation: "Man", type: "Medinan" },
  { id: 77, nameEn: "Al-Mursalat", translation: "Those Sent Forth", type: "Meccan" },
  { id: 78, nameEn: "An-Naba", translation: "The Great News", type: "Meccan" },
  { id: 79, nameEn: "An-Nazi'at", translation: "Those Who Pull Out", type: "Meccan" },
  { id: 80, nameEn: "Abasa", translation: "He Frowned", type: "Meccan" },
  { id: 81, nameEn: "At-Takwir", translation: "The Overthrowing", type: "Meccan" },
  { id: 82, nameEn: "Al-Infitar", translation: "The Cleaving", type: "Meccan" },
  { id: 83, nameEn: "Al-Mutaffifin", translation: "Those Who Deal in Fraud", type: "Meccan" },
  { id: 84, nameEn: "Al-Inshiqaq", translation: "The Splitting Asunder", type: "Meccan" },
  { id: 85, nameEn: "Al-Buruj", translation: "The Stars", type: "Meccan" },
  { id: 86, nameEn: "At-Tariq", translation: "The Night-Comer", type: "Meccan" },
  { id: 87, nameEn: "Al-A'la", translation: "The Most High", type: "Meccan" },
  { id: 88, nameEn: "Al-Ghashiyah", translation: "The Overwhelming", type: "Meccan" },
  { id: 89, nameEn: "Al-Fajr", translation: "The Dawn", type: "Meccan" },
  { id: 90, nameEn: "Al-Balad", translation: "The City", type: "Meccan" },
  { id: 91, nameEn: "Ash-Shams", translation: "The Sun", type: "Meccan" },
  { id: 92, nameEn: "Al-Lail", translation: "The Night", type: "Meccan" },
  { id: 93, nameEn: "Ad-Duhaa", translation: "The Forenoon", type: "Meccan" },
  { id: 94, nameEn: "Ash-Sharh", translation: "The Opening Forth", type: "Meccan" },
  { id: 95, nameEn: "At-Tin", translation: "The Fig", type: "Meccan" },
  { id: 96, nameEn: "Al-Alaq", translation: "The Clot", type: "Meccan" },
  { id: 97, nameEn: "Al-Qadr", translation: "The Night of Decree", type: "Meccan" },
  { id: 98, nameEn: "Al-Bayyinah", translation: "The Clear Evidence", type: "Medinan" },
  { id: 99, nameEn: "Az-Zalzalah", translation: "The Earthquake", type: "Medinan" },
  { id: 100, nameEn: "Al-Adiyat", translation: "The Runners", type: "Meccan" },
  { id: 101, nameEn: "Al-Qari'ah", translation: "The Striking Hour", type: "Meccan" },
  { id: 102, nameEn: "At-Takathur", translation: "The Piling Up", type: "Meccan" },
  { id: 103, nameEn: "Al-Asr", translation: "The Time", type: "Meccan" },
  { id: 104, nameEn: "Al-Humazah", translation: "The Slanderer", type: "Meccan" },
  { id: 105, nameEn: "Al-Fil", translation: "The Elephant", type: "Meccan" },
  { id: 106, nameEn: "Quraysh", translation: "Quraysh", type: "Meccan" },
  { id: 107, nameEn: "Al-Ma'un", translation: "The Small Kindnesses", type: "Meccan" },
  { id: 108, nameEn: "Al-Kawthar", translation: "The Abundance", type: "Meccan" },
  { id: 109, nameEn: "Al-Kafirun", translation: "The Disbelievers", type: "Meccan" },
  { id: 110, nameEn: "An-Nasr", translation: "The Help", type: "Medinan" },
  { id: 111, nameEn: "Al-Masad", translation: "The Palm Fiber", type: "Meccan" },
  { id: 112, nameEn: "Al-Ikhlas", translation: "The Sincerity", type: "Meccan" },
  { id: 113, nameEn: "Al-Falaq", translation: "The Daybreak", type: "Meccan" },
  { id: 114, nameEn: "An-Nas", translation: "Mankind", type: "Meccan" },
];

/**
 * Quick lookup map: surah number → metadata
 */
export const SURAH_META_MAP = new Map(SURAH_META.map((s) => [s.id, s]));
